### ISSUE TITLE
Feature Request: Customizable Keyboard Short Cuts

### ISSUE THREAD

**Issue by jorisw** [joshjon/nocturnal#11]
A similar app called [QuickShade](https://apps.apple.com/us/app/quickshade/id931571202?mt=12) allows me to add shortcut keys for the brightness, which is very helpful once it gets dark outside. I have them mapped to F5 and F6, two keys that are vacant by default on Apple's external full size keyboard.

![image](https://user-images.githubusercontent.com/30017/80787710-8ebfc600-8b87-11ea-8f28-66b394317fe0.png)

**Comment by joshjon** [comment]
@jorisw this has been added to Nocturnal v1.1. Download the latest release to try it out 😁

**Comment by jorisw** [comment]
Works great!
