### ISSUE TITLE
Support for Mojave?

### ISSUE THREAD

**Issue by eSoares** [joshjon/nocturnal#21]
Hello,

Your app looks great, and is exactly what I was looking for (hiding the touchbar sometimes and easy and fast control of screen brightness). Unfortunately I'm stuck at Mojave (10.14).
Looking at some of the code looks there is already support for Mojave (https://github.com/joshjon/nocturnal/blob/master/Nocturnal/Application/TouchBar/TouchBar.swift). 
Night Shift was also introduced in 10.14, would it be possible to compile and run the app in Mojave?

(I don't have any experience compiling Swift or MacOS apps, otherwise would try it myself.)

**Comment by joshjon** [comment]
Hey there, I'm glad to hear your interested in trying Nocturnal! I have just created a new branch where I have a archived a version of the app that has a lower deployment target which should support Mojave. I have tested this on Catalina with no issues found, however, I do not have the ability to test this out on Mojave. If you would be willing to confirm that this archive works for you then I would be happy to create a new release for it.

You can either download the archive directly [here](https://github.com/joshjon/nocturnal/raw/support-earlier-macos/Product/Nocturnal-1.1.1.zip), or you can checkout the branch `support-earlier-macos` and find it at `/Product/Nocturnal-1.1.1.zip`

**Comment by eSoares** [comment]
Thanks for the fast response. 😃 

Just downloaded and gave it a quick spin. From what I have found it works good 👍 
- Touchbar hiding works;
- Screen dimming works;
- Night Shift adjustment works;

Note: I have my mackbook pro and an external monitor connected, when dimming/night shift is changed affects both monitors. Don't know if should be possible to control each one individually.

**Comment by joshjon** [comment]
I have published release 1.1.1 with the new changes. Thanks for he help!

> Note: I have my mackbook pro and an external monitor connected, when dimming/night shift is changed affects both monitors. Don't know if should be possible to control each one individually.

Yes this is the intended behaviour as it makes the most sense to globally control all monitors in my opinion. However, controlling monitors individually could maybe something to add in the future 😁.
