### ISSUE TITLE
Apple says you will damage my computer

### ISSUE THREAD

**Issue by deadlyicon** [joshjon/nocturnal#24]
![image](https://user-images.githubusercontent.com/8385/86828717-71f0b480-c048-11ea-8d93-c6eb84434f5c.png)

**Comment by joshjon** [comment]
As per your comment on reddit, closing this issue as the app installed in the screenshot is a completetly different app that just has the same name.

> I installed this via Homebrew and upon launching it for the first time I got a warning saying this app will "damage your computer" so I uninstalled it.
EDIT: turns out that's a different app with the same name. Ignore me!
