### ISSUE TITLE
After mac wakes up, the overlay resolution is too small

### ISSUE THREAD

**Issue by skeletoooooor** [joshjon/nocturnal#9]
Sometimes, when the Mac wakes up, the overlay resolution is too small, showing a small darker area in the middle of the screen.
I must say, that I'm using an external 38" ultra wide screen.

Maybe there's a way to fix it?
Thanks

**Comment by joshjon** [comment]
Hey, sounds like it should be fixable but unfortunately I don't have an ultra wide screen to test this with. I can try and look into this issue, but am currently on vacation so I will most likely need to wait until I get back!

**Comment by joshjon** [comment]
@skeletoooooor this has been addressed in Nocturnal v1.1. Download the latest release to try it out 😁
